# Assignment-1: Transformations and representations

Team Name: Sudarshan_Rishabh

Roll number: 2021701008 2021701030

# Instructions

- Code must be written in Python in Jupyter Notebooks. We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. See `Set Up` for detailed step-by-step instructions about the installation setup.
- Save all your results in ```results/<question_number>/<sub_topic_number>/```
- The **References** section provides you with important resources to solve the assignment.
- For this assignment, you will be using Open3D extensively. Refer to [Open3D Documentation](http://www.open3d.org/docs/release/): you can use the in-built methods and **unless explicitly mentioned**, don't need to code from scratch for this assignment. 
- Make sure your code is modular since you may need to reuse parts for future assignments.
- Answer the descriptive questions in your own words with context & clarity. Do not copy answers from online resources or lecture notes.
- The **deadline** for this assignment is on 11/09/2021 at 11:55pm. Please note that there will be no extensions.
- Plagiarism is **strictly prohibited**.


# Submission Instructions

1. Make sure your code runs without any errors after reinitializing the kernel and removing all saved variables.
2. After completing your code and saving your results, zip the folder with name as ``Team_<team_name>_MR2021_Assignment_<assignment_number>.zip``

# Set Up

We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. All assignments will be python based, hence familiarising yourself with Python is essential.


## Setting up Anaconda environment (Recommended)

1. Install Anaconda or Miniconda from [here](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) depending on your requirements.
2. Now simply run `conda env create -f environment.yml` in the current folder to create an environment `mr_assignment1` (`environment.yml` can be found in `misc/`).
3. Activate it using `conda activate mr_assignment1`.

## Setting up Virtual environment using venv

You can also set up a virtual environment using venv

1. Run `sudo apt-get install python3-venv` from command line.
2. `python3 -m venv ~/virtual_env/mr_assignment1`. (you can set the environment path to anything)
3. `source ~/virtual_env/mr_assignment1/bin/activate`
4. `pip3 install -r requirements.txt` from the current folder (`requirements.txt` can be found in `misc/`).

In [2]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


# 1. Getting started with Open3D

Open3D is an open-source library that deals with 3D data, such as point clouds, mesh. We'll be using Open3D frequently as we work with point clouds. Let's start with something simple:

<img src="misc/bunny.jpg" alt="drawing" width="200"/>

1. Read the Stanford Bunny file (in `data/`) given to you and visualise it using Open3D.
2. Convert the mesh to a point cloud and change the colour of points.
3. Set a predefined viewing angle (using Open3D) for visualization and display the axes while plotting.
4. Scale, Transform, and Rotate the rabbit (visualise after each step).
5. Save the point cloud as bunny.pcd.

In [1]:
# 1. Read the Stanford Bunny file 

import numpy as np
import open3d as o3d
import copy


pcd = o3d.io.read_point_cloud("/home/rishabh/Downloads/codes/bunny.ply")
print(pcd)
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
PointCloud with 35947 points.


In [2]:
# 2. Convert the mesh to a point cloud
o3d.visualization.draw_geometries([pcd])

In [3]:
# 3. Set a predefined viewing angle and display the axes 

vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(pcd)
coordinates = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.1, origin=np.array([0., 0., 0.]))
vis.add_geometry(coordinates)
vis_cntrl = ctr = vis.get_view_control()
ctr.change_field_of_view(step=60)
vis.run()

In [3]:
# 4. Scale
pcd_scale = copy.deepcopy(pcd).translate((0.10,0.10,0.10), relative=False) # translating for better visulization  / center variable can also be changed 
pcd_scale.scale(5 , center=(0,0,0))
o3d.visualization.draw_geometries([pcd, pcd_scale])

In [4]:
# 4. Transform
pcd_translate = copy.deepcopy(pcd).translate((0.10,0.10,0.10), relative=False)
o3d.visualization.draw_geometries([pcd, pcd_translate])

In [5]:
# 4. Rotate
pcd_rotate = copy.deepcopy(pcd).translate((0.10,0.10,0.10), relative=False) # translating for better visulization  / center variable can also be changed 
R = pcd.get_rotation_matrix_from_xyz((np.pi/2,0,np.pi/4))
pcd_rotate.rotate(R, center=(0,0,0))
o3d.visualization.draw_geometries([pcd, pcd_rotate])

In [6]:
#color change
pcd.paint_uniform_color([1, 0.706, 0])
o3d.visualization.draw_geometries([pcd])

In [9]:
# 5. Save the point cloud as bunny.pcd.
o3d.io.write_point_cloud("bunny.pcd", pcd )

True

# 2. Transformations and representations

## a) Euler angles
1. Write a function that returns a rotation matrix given the angles $\alpha$, $\beta$, and $\gamma$ in radians (X-Y-Z)

2. Solve for angles using ```fsolve from scipy``` for three initializations of your choice and compare.
$$M(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0.26200263 & -0.19674724 & 0.944799 \\0.21984631 & 0.96542533 & 0.14007684 \\
    -0.93969262 & 0.17101007 & 0.29619813\end{array}\right] 
$$

$$N(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0 & -0.173648178 &  0.984807753 \\0 & 0.984807753 & 0.173648178 \\
    -1 & 0 & 0\end{array}\right] 
$$

3. What is a Gimbal lock? 

4. Show an example where a Gimbal lock occurs and visualize the Gimbal lock on the given bunny point cloud. You have to show the above by **animation** (cube rotating along each axis one by one).
    - *Hint: Use Open3D's non-blocking visualization and discretize the rotation to simulate the animation. For example, if you want to rotate by $30^{\circ}$ around a particular axis, do in increments of $5^{\circ}$ 6 times to make it look like an animation.*


In [10]:
#1. Write a function that returns a rotation matrix given the angles 𝛼, 𝛽, and 𝛾 in radians (X-Y-Z)

import numpy as np
import math
from scipy.optimize import fsolve

alpha_in = math.radians(90) #X
beta_in = math.radians(90)  #Y
gamma_in = math.radians(0) #Z
s =math.sin
c= math.cos
def calculate_R( angles):
  alpha = angles[0]
  beta = angles[1]
  gamma = angles[2]
  R_x = np.array( [ [ 1 , 0 , 0 ] ,
                   [ 0 , c(alpha) , -s(alpha) ]  , 
                   [0 , s(alpha) , c(alpha)]])
    
  R_y = np.array( [ [ c(beta) , 0 , s(beta) ] ,
                   [ 0 ,1 ,0 ] ,
                   [ -s(beta) , 0 , c(beta)]])
  R_z = np.array( [ [  c(gamma) , -s(gamma) , 0 ] , 
                   [s(gamma) , c(gamma) , 0 ] ,
                   [0 ,0, 1]]  )
  R = R_z@R_y@R_x

  return R

angles = np.array( [alpha_in, beta_in, gamma_in]) # X, Y, Z
R = calculate_R(angles)
print(R)

[[ 6.12323400e-17  1.00000000e+00  6.12323400e-17]
 [ 0.00000000e+00  6.12323400e-17 -1.00000000e+00]
 [-1.00000000e+00  6.12323400e-17  3.74939946e-33]]


In [11]:
# 2a. Solve for angles using fsolve from scipy 
# For M matrix

from scipy.optimize import fsolve
import numpy as np
import math
from scipy.spatial.transform import Rotation as R

alpha_init = 50*np.pi/180 
beta_init = 100*np.pi/180  
gamma_init = 0*np.pi/180 
sq = math.sqrt
euler_angles = np.array( [ alpha_init , beta_init ,gamma_init ]) # rotation in X, Y, Z

target_R = np.array( [ [  0.26200263 , -0.19674724 , 0.944799 ] ,
		[0.21984631  , 0.96542533 , 0.14007684 ] , 
		[ -0.93969262 , 0.17101007 , 0.29619813 ] ])

v1 = np.array( [ 1,1,1 ] )
v1 = v1/np.linalg.norm( v1)
target_v1 = target_R@v1

v2 = np.array( [ 1,1,0 ] )
v2 = v2/np.linalg.norm( v2)
target_v2 = target_R@v2

v3 = np.array( [ 0,1,0 ] )
v3 = v3/np.linalg.norm( v3)
target_v3 = target_R@v3

def determine_euler_angles( angles):
	alpha = angles[0]  # X
	beta = angles[1] #Y
	gamma = angles[2] #Z
	s = math.sin
	c = math.cos

	R_x = np.array( [ [ 1,0 ,0  ]  ,
					   [ 0 , c(alpha) , -s(alpha)] , 
					   [ 0 , s(alpha) , c(alpha)] ]  )
	R_y = np.array( [ [ c(beta),0 ,s(beta)  ]  ,
					   [ 0 , 1 , 0] , 
					   [ -s(beta) , 0 , c(beta)] ]  )
	R_z = np.array( [ [ c(gamma) , -s(gamma) , 0 ] , 
						[s(gamma) , c(gamma) , 0] , 
						[0 ,0 ,1] ] )

	R = R_z@R_y@R_x

	curr_v1 = R@v1 
	curr_v2 = R@v2 
	curr_v3 = R@v3 

	residual_x1 = np.linalg.norm( curr_v1[0] - target_v1[0])
	residual_y1 = np.linalg.norm(curr_v1[1] - target_v1[1])
	residual_z1 = np.linalg.norm(curr_v1[2] - target_v1[2])
	# print(residual_x , residual_y , residual_z )

	residual_x2 = np.linalg.norm( curr_v2[0] - target_v2[0])
	residual_y2 = np.linalg.norm(curr_v2[1] - target_v2[1])
	residual_z2 = np.linalg.norm(curr_v2[2] - target_v2[2])

	residual_x3 = np.linalg.norm( curr_v3[0] - target_v3[0])
	residual_y3 = np.linalg.norm(curr_v3[1] - target_v3[1])
	residual_z3 = np.linalg.norm(curr_v3[2] - target_v3[2])

	return residual_x1+residual_x2+residual_x3 , residual_y1+residual_y2+residual_y3 , residual_z1+residual_z2+residual_z3

for i in range(3):
	res_angles = fsolve(determine_euler_angles , euler_angles*(i ))
	print(" Actual Output  = " + str( res_angles*180/np.pi))

	res_angles = res_angles*180/np.pi
	res_angles_alpha  =   (res_angles[0]/360 - int(res_angles[0]/360 )  )*360
	res_angles_beta  =   (res_angles[1]/360 - int(res_angles[1]/360 ) )*360
	res_angles_gamma  =   (res_angles[2]/360 - int(res_angles[2]/360 ) )*360

	least_Res_angle = [ res_angles_alpha , res_angles_beta , res_angles_gamma]
	print("  Output in the least form  " + str( least_Res_angle))

	M = R.from_matrix( [ [  0.26200263 , -0.19674724 , 0.944799 ] ,
		[0.21984631  , 0.96542533 , 0.14007684 ] , 
		[ -0.93969262 , 0.17101007 , 0.29619813 ] ])

	N = R.from_matrix( [ [  0 , -0.173648178 , 0.984807753  ]  , 
	[ 0 , 0.96542533 ,  0.14007684 ] , 
	[ -1  , 0 , 0 ]  ])

	print( " Verification of Output = "  + str( M.as_euler('xyz', degrees=True))) 
	print(" *************************")

 Actual Output  = [29.9999986  69.99999971 39.99999858]
  Output in the least form  [29.999998599581893, 69.99999971020256, 39.999998580206736]
 Verification of Output = [30.00000046 70.00000021 40.00000028]
 *************************
 Actual Output  = [389.99999822  69.99999974 399.9999986 ]
  Output in the least form  [29.999998220413737, 69.999999744902, 39.999998600052024]
 Verification of Output = [30.00000046 70.00000021 40.00000028]
 *************************
 Actual Output  = [29.99999791 69.99999925 39.99999847]
  Output in the least form  [29.99999790898721, 69.99999925223901, 39.999998467017726]
 Verification of Output = [30.00000046 70.00000021 40.00000028]
 *************************


/home/rishabh/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)


In [12]:
# 2b. Solve for angles using fsolve from scipy 
# For N matrix

from scipy.optimize import fsolve
import numpy as np
import math
from scipy.spatial.transform import Rotation as R

alpha_init = np.pi/180 
beta_init = np.pi/180  
gamma_init = np.pi/180 
sq = math.sqrt

euler_angles = np.array( [ alpha_init , beta_init ,gamma_init ]) # rotation in X, Y, Z
target_R = np.array( [ [  0 , -0.173648178 , 0.984807753  ]  , 
	[ 0 , 0.96542533 ,  0.14007684 ] , 
	[ -1  , 0 , 0 ]  ] )

v1 = np.array( [ 1,1,1 ] )
v1 = v1/np.linalg.norm( v1)
target_v1 = target_R@v1

v2 = np.array( [ 1,1,0 ] )
v2 = v2/np.linalg.norm( v2)
target_v2 = target_R@v2

v3 = np.array( [ 0,1,0 ] )
v3 = v3/np.linalg.norm( v3)
target_v3 = target_R@v3

def determine_euler_angles( angles):

	alpha = angles[0]  # X
	beta = angles[1] #Y
	gamma = angles[2] #Z
	s = math.sin
	c = math.cos

	R_x = np.array( [ [ 1,0 ,0  ]  ,
					   [ 0 , c(alpha) , -s(alpha)] , 
					   [ 0 , s(alpha) , c(alpha)] ]  )
	R_y = np.array( [ [ c(beta),0 ,s(beta)  ]  ,
					   [ 0 , 1 , 0] , 
					   [ -s(beta) , 0 , c(beta)] ]  )
	R_z = np.array( [ [ c(gamma) , -s(gamma) , 0 ] , 
						[s(gamma) , c(gamma) , 0] , 
						[0 ,0 ,1] ] )

	R = R_z@R_y@R_x
	curr_v1 = R@v1 
	curr_v2 = R@v2 
	curr_v3 = R@v3 

	residual_x1 = np.linalg.norm( curr_v1[0] - target_v1[0])
	residual_y1 = np.linalg.norm(curr_v1[1] - target_v1[1])
	residual_z1 = np.linalg.norm(curr_v1[2] - target_v1[2])
	# print(residual_x , residual_y , residual_z )

	residual_x2 = np.linalg.norm( curr_v2[0] - target_v2[0])
	residual_y2 = np.linalg.norm(curr_v2[1] - target_v2[1])
	residual_z2 = np.linalg.norm(curr_v2[2] - target_v2[2])

	residual_x3 = np.linalg.norm( curr_v3[0] - target_v3[0])
	residual_y3 = np.linalg.norm(curr_v3[1] - target_v3[1])
	residual_z3 = np.linalg.norm(curr_v3[2] - target_v3[2])

	return residual_x1+residual_x2+residual_x3 , residual_y1+residual_y2+residual_y3 , residual_z1+residual_z2+residual_z3

for i in range(3):

	res_angles = fsolve(determine_euler_angles , euler_angles*(i ))
	print(" Actual Output  = " + str( res_angles*180/np.pi))
	res_angles = res_angles*180/np.pi
	res_angles_alpha  =   (res_angles[0]/360 - int(res_angles[0]/360 )  )*360
	res_angles_beta  =   (res_angles[1]/360 - int(res_angles[1]/360 ) )*360
	res_angles_gamma  =   (res_angles[2]/360 - int(res_angles[2]/360 ) )*360
	least_Res_angle = [ res_angles_alpha , res_angles_beta , res_angles_gamma]
	print("  Output in the least form  " + str( least_Res_angle))

	N = R.from_matrix( [ [  0 , -0.173648178 , 0.984807753  ]  , 
	[ 0 , 0.96542533 ,  0.14007684 ] , 
	[ -1  , 0 , 0 ]  ])

	print( " Verification of Output = "  + str( N.as_euler('xyz', degrees=True))) 
	print(" *************************")

 Actual Output  = [35.74907477 90.76606127 45.27806769]
  Output in the least form  [35.74907477427767, 90.76606126568731, 45.27806768864778]
 Verification of Output = [-64.54086106  88.87904355 -55.4591339 ]
 *************************
 Actual Output  = [82.93814462 90.66720953 92.86738765]
  Output in the least form  [82.93814462187515, 90.66720953390856, 92.86738764752302]
 Verification of Output = [-64.54086106  88.87904355 -55.4591339 ]
 *************************
 Actual Output  = [ 92.25823606  90.69028314 102.25051855]
  Output in the least form  [92.25823606224132, 90.69028313681312, 102.2505185499182]
 Verification of Output = [-64.54086106  88.87904355 -55.4591339 ]
 *************************


3. Gimbal lock\
When two rotational axes are completely aligned (or parallel) with each other it leads to the gimbal lock configuration, where 1DOF is lost.

In [13]:
# 4. visualize the Gimbal lock on the given bunny point cloud

import open3d as o3d
import numpy as np
import math
import time
from scipy.linalg import expm, sinm, cosm
from scipy.spatial.transform import Rotation as R
from scipy.spatial.transform import Slerp
import copy
sq = math.sqrt

vis = o3d.visualization.Visualizer()
vis.create_window()

bunny = o3d.io.read_point_cloud("/home/rishabh/Downloads/codes/bunny.ply")
# vis.add_geometry(bunny)

coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame( size=0.2, origin=[0, 0, 0] )
# vis.add_geometry(coordinate_frame)

coordinate_frame_copy = copy.deepcopy(coordinate_frame)
# vis.add_geometry(coordinate_frame_copy)

resolution = 30
rad_angle = 0 
sq = math.sqrt
rotation_sequence = np.array( [ [  30 , 40  , 60   ]  ,  ## Initial rotation demonstration without gimbal lock
                                 [ 30 , 90 , 360  ]  ,  ## Gimbal Lock 
                                 [60, -90, 360 ] ]) 

def perform_rotation( R, resolution):
  for increment in range(resolution):
    bunny.rotate(R)
    # coordinate_frame_copy.rotate(R)
    vis.update_geometry(bunny)
    # vis.update_geometry(coordinate_frame_copy)
    vis.poll_events()
    vis.update_renderer()
    time.sleep(0.1)    

for angles in rotation_sequence:
  vis.add_geometry(bunny)
  vis.add_geometry(coordinate_frame)
  vis.add_geometry(coordinate_frame_copy)

  alpha =  angles[0]*np.pi/180 # X
  beta = angles[1]*np.pi/180 # Y
  gamma = angles[2]*np.pi/180 # Z
  euler_angles = np.array( [ alpha , beta ,gamma ]) # rotation in X, Y, Z

  # we will perform rotations in the sequence X, Y, Z
  original_axis = np.array( [ [ 1 , 0 , 0 ] ,  #X
                            [0 ,1, 0]  ,  #Y
                              [0,0,1] ]) # Z
  # rotate around x axis 

  R_x = bunny.get_rotation_matrix_from_axis_angle( original_axis[0].T*(alpha/resolution) )
  if alpha!= 0 :
   perform_rotation( R_x , resolution)
  print(" Complete X rotation " + str(alpha))

  R_after_rotation_around_x = bunny.get_rotation_matrix_from_xyz( ( alpha , 0 , 0 ))

  axis_new_after_x_rotation = np.dot( R_after_rotation_around_x , original_axis)
  # rotate around y axis 
  time.sleep(2)

  R_y = bunny.get_rotation_matrix_from_axis_angle( axis_new_after_x_rotation[1].T*(beta/resolution) )
  if beta !=0 :
    perform_rotation( R_y , resolution)
  R_after_rotation_around_x_and_y = bunny.get_rotation_matrix_from_xyz( ( alpha , beta , 0 ))
  axis_new_after_x_and_y_rotation = np.dot( R_after_rotation_around_x_and_y , original_axis)

  print(" Complete Y rotation "  + str(beta))
  # rotate around z axis 
  time.sleep(2)

  R_z = bunny.get_rotation_matrix_from_axis_angle( axis_new_after_x_and_y_rotation[2].T*gamma/resolution )
  if gamma != 0 :
    perform_rotation( R_z , resolution)
  print(" Complete Z rotation " +str(gamma) )
  vis.clear_geometries()
  time.sleep(5)
  print(" *********************** ")
  print(" COmpleted the iteration ")
  print(" *********************** ")

 Complete X rotation 0.5235987755982988
 Complete Y rotation 0.6981317007977318
 Complete Z rotation 1.0471975511965976
 *********************** 
 COmpleted the iteration 
 *********************** 
 Complete X rotation 0.5235987755982988
 Complete Y rotation 1.5707963267948966


KeyboardInterrupt: 

## b) Quaternions

1. What makes Quaternions popular in graphics? 
2. Convert a rotation matrix to quaternion and vice versa. Do not use inbuilt libraries for this question.
3. Perform matrix multiplication of two $\mathcal{R}_{3 \times 3}$ rotation matrices and perform the same transformation in the quaternion space. Verify if the final transformation obtained in both the cases are the same.
4. Try to interpolate any 3D model (cube / bunny / not sphere obviously!!) between two rotation matrices and visualize!

The above questions require you to **code your own functions** and **only verify** using inbuilt functions.

## Solution

1.Quaternions are popular because\
a) Quaternion representaion can overcome the gimbal lock problem.\
b) It is more memory efficient, quaternion require 4 parameters to explain arotation where as a rotation matrix requires 9 elements.\
c) They are unique and euler angles are not.\
d) Provides a seamless way to interpolate between two 3D orientations, thatlacks the ambiguities of Euler angles and issues related to the normaliza-tion and numerical instabilities of the rotation matrix.

In [14]:
#2 Rotation matrix to quaternion

import numpy as np
def Quaternion_to_RotationMatrix(q):
    n = 1/np.sqrt(q[0]*q[0] + q[1]*q[1] + q[2]*q[2] + q[3]*q[3]) #Normalize
    qw = q[0]*n
    qx = q[1]*n
    qy = q[2]*n
    qz = q[3]*n
    
    RotationMatrix = np.array([[1 - 2*(qz*qz + qy * qy) , -2*(qz*qw - qy*qx), 2*(qy*qw + qz*qx)],
                           [2*(qx*qy + qw*qz),  1 - 2*(qz*qz + qx*qx) , 2*(qy*qy - qx*qw)],
                           [2*(qx*qz - qw*qy), 2*(qy*qz + qw*qx), 1 - 2*(qy*qy + qx*qx)]])
                            
    return RotationMatrix

q = np.array([0.7, 0.462, 0.191, -0.462])
R = Quaternion_to_RotationMatrix(q)
print(R)

[[ 0.47570143  0.86355231 -0.16728885]
 [-0.49332001  0.10446427 -0.60190545]
 [-0.72824688  0.49332001  0.47570143]]


In [15]:
#2 Quaternion to Rotation matrix
# https://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/
# https://d3cw3dd2w32x2b.cloudfront.net/wp-content/uploads/2015/01/matrix-to-quat.pdf
# http://what-when-how.com/advanced-methods-in-computer-graphics/quaternions-advanced-methods-in-computer-graphics-part-3/

def RotationMatrix_to_Quaternion(R):
    m00 = R[0,0]
    m01 = R[0,1]
    m02 = R[0,2]
    m10 = R[1,0]
    m11 = R[1,1]
    m12 = R[1,2]
    m20 = R[2,0]
    m21 = R[2,1]
    m22 = R[2,2]
    
    trace = m00 + m11 + m22
    if(trace > 0):
        sq = np.sqrt(trace + 1)*2
        qw = 0.25*sq
        qx = (m21 - m12)/sq
        qy = (m02 - m20)/sq
        qz = (m10 - m01)/sq
        
    elif(m00 > m11 and m00 > m22):
        sq = np.sqrt(1 + m00 - m11 - m22)*2
        qw = (m21 - m12)/sq
        qx = 0.25*sq
        qy = (m01 + m10)/sq
        qz = (m02 + m20)/sq
        
    elif(m11 > m22):
        sq = np.sqrt(1 + m11 - m00 - m22)*2
        qw = (m02 - m20)/sq
        qx = (m01 + m10)/sq
        qy = 0.25*sq
        qz = (m12 + m21)/sq
        
    else:
        sq = np.sqrt(1 + m22 - m00 - m11)*2
        qw = (m10 - m01)/sq
        qx = (m02 + m20)/sq
        qy = (m12 + m21)/sq
        qz = 0.25*sq

    q = np.array([qw, qx,qy,qz])
    return q

q1 = (RotationMatrix_to_Quaternion(R))
print(" Transformed Quaternion  = " + str(q1))
print(" Original Quaternion  = " + str(q))
print("Both quaternion are not exactly same")
# R1 = Quaternion_to_RotationMatrix(q1)
# print(R1)

 Transformed Quaternion  = [ 0.71691477  0.38192318  0.19561532 -0.47316375]
 Original Quaternion  = [ 0.7    0.462  0.191 -0.462]
Both quaternion are not exactly same


In [16]:
#  3. Verify if the final transformation obtained by R matrix multiplication and Quaternion

quat_1 = np.array([0.733, 0.462 , 0.191, 0.462])
quat_2 = np.array([1, 0 , 0, 0])

rot_1 = Quaternion_to_RotationMatrix(quat_1)
rot_2 = Quaternion_to_RotationMatrix(quat_2)

# quaternion multiplication
quat0 = quat_1[0]*quat_2[0] - quat_1[1]*quat_2[1] - quat_1[2]*quat_2[2] - quat_1[3]*quat_2[3]
quat1 = quat_1[0]*quat_2[1] + quat_1[1]*quat_2[0] - quat_1[2]*quat_2[3] + quat_1[3]*quat_2[2]
quat2 = quat_1[0]*quat_2[2] + quat_1[1]*quat_2[3] + quat_1[2]*quat_2[0] - quat_1[3]*quat_2[1]
quat3 = quat_1[0]*quat_2[3] - quat_1[1]*quat_2[2] + quat_1[2]*quat_2[1] + quat_1[3]*quat_2[0]
quat = np.array([quat0,quat1,quat2,quat3])

rot = np.dot(rot_2,rot_1)   #not commutative
quat_conversion = RotationMatrix_to_Quaternion(rot)

print(quat)
print(quat_conversion)

#note: R matrix by [- quaternion] = R matrix by [quaternion]

# SOLUTION:- Both are not exactly same. Transforming a Quaternion to Rotation Matrix and again changing 
# the same Rotation matrix back to Quaternion will not be exactly same as original one. 

[0.733 0.462 0.191 0.462]
[0.73275896 0.49714411 0.19093719 0.46184808]


#4 . Interpolate any 3D model between two rotation matrices

For this question we present two methods 

1) Here we obtain the logarithmic map of the corresponding rotation matrix, and we divide the resulting rotation   into uniform steps and execute the given rotations step by step. This method although arrives at the final rotation matrix, the interpolation is not smooth. 

2) SLERP: scipy library provides a convinent method to perform rotation interpolation using quaternions.  

In [17]:
# 4. Interpolate any 3D model between two rotation matrices and visualize

import open3d as o3d
import numpy as np
import math
sq = math.sqrt
import time
from scipy.linalg import expm, sinm, cosm
from scipy.spatial.transform import Rotation as R
from scipy.spatial.transform import Slerp

init_v = np.array([ 0 ,1,0])

# R_init = np.identity(3)
'''
R_init = np.array( [ [ 1, 0, 0 ] , 
                        [0,1,0] , 
                          [0,0,1]   ])

R_final = np.array([ [ 0 , 1 , 0  ] , 
                      [ 0 ,0 ,1  ], 
                      [ 1 , 0 , 0]   ])

R_mid = np.array([ [ 1 , 0 , 0  ] , 
                      [ 0 ,0 ,1  ], 
                      [ 0 , 1 , 0]   ])

'''
key_rots = R.random(2, random_state=2342345) # generate two quaternions 
R_init = key_rots[0].as_matrix()
R_final = key_rots[1].as_matrix()

def logarithmic_map( R):
    phi  = math.acos( (np.trace(R) -1)/2  )
    # print(phi)
    u = (R - R.T)/(2*math.sin(phi))
#     print(u)
    U = np.array( [   u[2][1] , u[0][2] , u[1][0]   ] )
    return phi , U

def get_delta_SO3(time_t):
    w = U_final #np.array( [ 1,0,0  ])
    w = w*time_t
    so3 = np.array( [  [ 0, -w[2] , w[1]  ]  , 
                        [ w[2] , 0 , -w[0]  ] ,
                        [-w[1] , w[0] , 0 ]   ]  )
    # print(so3)
    del_SO3 = expm( so3)
    return del_SO3

def get_rotation_matrix_at_time_t( R_t_minus_1 , time_t):
    R_delta_t = get_delta_SO3(time_t)
    # R_t =  np.matmul(  R_t_minus_1 , R_delta_t )  #R_t_minus_1@R_delta_t
    # print( R_delta_t)
    return R_delta_t

# phi_int , U_init = logarithmic_map( R_init)
phi_final , U_final = logarithmic_map( R_final)

# Create Open3d visualization window
vis = o3d.visualization.Visualizer()
vis.create_window()

# create sphere geometry
bunny =  o3d.io.read_point_cloud("/home/rishabh/Downloads/codes/bunny.ply")
 #o3d.geometry.TriangleMesh.create_box(width=0.2, height=0.2, depth=0.5 ) #o3d.geometry.TriangleMesh.create_cube()
vis.add_geometry(bunny)

# create coordinate frame
coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame()
vis.add_geometry(coordinate_frame)

# R_init = np.identity(3)
R = R_init
curr_tf = R
prev_tf = None
step = 0
resolution = phi_final/20

for i in range( 20):
    time_t = i*resolution
    # return sphere1 to original position (0,0,0)
    R = curr_tf
    step +=1
#     print(step)
    if prev_tf is not None:
        bunny.transform(np.linalg.inv(prev_tf))
    # transform bazed on curr_z tf
    curr_tf = get_rotation_matrix_at_time_t(R , time_t)
    # sphere1.transform(curr_tf)
    bunny.rotate(curr_tf)
#     print(curr_tf)
    vis.update_geometry(bunny)
    vis.poll_events()
    vis.update_renderer()
    time.sleep(0.5)

## Interpolation using SLERP 
key_times = [0, 3]
# key_times = np.arange( 0,10, 0.1)
slerp = Slerp(key_times, key_rots)
times = np.arange( 0,3, 0.20)
interp_rots = slerp(times)
R_interpolate = interp_rots.as_matrix()
vis.create_window()
vis.add_geometry(bunny)
vis.add_geometry(coordinate_frame)

for Rot in ( R_interpolate):
    bunny.rotate(Rot)
    vis.update_geometry(bunny)
    vis.poll_events()
    vis.update_renderer()
    time.sleep(1)

KeyboardInterrupt: 

## c) Exponential maps (Bonus)

1. What is the idea behind exponential map representation of rotation matrices?
2. Perform matrix exponentiation and obtain the rotation matrix to rotate a vector $P$ around $\omega$ for $\theta$ seconds.
$$
\omega = \begin{bmatrix}2 \\ 1 \\ 15 \end{bmatrix}
$$

$$
\theta = 4.1364
$$

3. Compute the logarithmic map (SO(3) to so(3)) of the rotation matrix to obtain the rotation vector and the angle of rotation
$$
\begin{bmatrix}
0.1 &  -0.9487 & 0.3 \\
0.9487 & 0.  & -0.3162 \\
0.3   &  0.3162  & 0.9 
\end{bmatrix}
$$
You can use inbuilt libraries **only to verify** your results.

### Solution:-
1. The idea behind exponential map representation of rotation matrices.

The Rotation matrices are not closed under the operation of addition or subtraction, hence the generic way of differentiation cannot defined for SO(3) groups. The exponential map allows us to properly define derivatives, perturbations, and velocities, and to manipulate them.  

Furthermore, it is possible to define
a continuous trajectory or path $r(t)$ in SO(3) that continuously rotates the rigid body from its initial orientation, r(0), to its current orientation, $r(t)$. Being continuous, it is legitimate to investigate the time-derivatives of such transformations. 

Exponential maps require only two quantities for a rotation parametrization, ie a unit vector "$e$" to represent the direction of an axis of rotation and an angle "$\theta$" denotes magnititude of rotation about the axis.

#Ref: https://www.cs.cmu.edu/~spiff/moedit99/expmap.pdf \
#Ref : https://arxiv.org/pdf/1711.02508.pdf  equation 80 , 81

In [18]:
# 2. Perform matrix exponentiation

import numpy as np
from scipy.linalg import expm, sinm, cosm
w = np.array( [ 2,1,15])
theta = 4.1364
w_theta = w*theta
so3 = np.array( [ [ 0 , -w_theta[2] , w_theta[1]  ] , 
                 [ w_theta[2] , 0 , -w_theta[0] ] , 
                 [ -w_theta[1] , w_theta[0] , 0 ]   ])

print( expm(so3))
#Reference : https://arxiv.org/pdf/1711.02508.pdf  equation 70

[[ 0.99506737  0.09902323 -0.00594386]
 [-0.09893593  0.99500189  0.01352466]
 [ 0.00725341 -0.01286989  0.99989087]]


In [20]:
# 3. Compute the logarithmic map (SO(3) to so(3))

R = np.array( [ [ 0.1 , -0.9487 , 0.3  ] , 
                [ 0.9487, 0 , -0.3162 ] , 
               [  0.3 , 0.3162 , 0.9]  ])

value = (np.trace(R) -1)/2
phi = np.arccos( value)

new_matrix = (R - R.T)/(2*np.sin(phi))
print(new_matrix)

u = [ new_matrix[2][1] , new_matrix[0][2] , new_matrix[0][1]  ]
print(u) 
print(phi)

#Reference : https://arxiv.org/pdf/1711.02508.pdf  equation 80 , 81

[[ 0.     -0.9487  0.    ]
 [ 0.9487  0.     -0.3162]
 [ 0.      0.3162  0.    ]]
[0.3162, 0.0, -0.9487]
1.5707963267948966


# 3. Data representations

## a) Octomaps

1. Why is an Octomap memory efficient?
2. When do we update an Octomap and why?
3. When would you likely use an octomap instead of a point cloud?
 

### Solutions 3 (a)
1. The octomap representation is memory efficient for the following reasons

A.  Pruning mechanism:  If all children of a node are at the same state (either free or occupied) then the children are pruned and the parent is retained.This leads to elimination of redundant information and a significant decrease in the number of nodes that need to be stored.

B.  OcTree Compression: This step is performed along with the pruning mechanism, the child nodes(memory) are regenerated on requirement basis i.e if a parent node is stable and the child nodes are pruned, the child nodes are regenerated only when measurements that contradict the state of inner node occur.

C.  Memory-Efficient Node Implementation: the memory layout of data is as follows. For a given node, a child pointer points to an array of 8 pointers and the inner nodes additionally store pointers of their children. In additon to this each node of an octree stores the probablity of occupancy. Note that the array is allocated only if the node has chilren and is not allocated for leaves, the leaf node of octree only stores only occupancy probablity and Null for pointer to child. 



### Solutions 3 (a)
2. The update of the Octomap depends upon the present state of the node

A.  Node is unknown and first observed: On observation of measurments form the sensor, the observations are continously integrated and a clamping update policy is used that defines upper and lower thresholds on the log odds value of occupancy. Once the integrated measurments cross the the necessary stable threshold the node is updated. 

B. Stable node updated through contradictory measurements: If all the inner nodes of a parent are stable then the nodes are pruned, only in future if measurments that contradict the present state of parent is integrated then its children are regenerated and updated accordingly. 

### Solutions 3 (a)
3. Octomap can be used instead of the point cloud in the following scenarios

A.  Notion  of  free  space:   Octomap  has  an  ability  to  represent  free  space,although we get information to the surface boundaries of an obstacle from point cloud it would be difficult to determine if a set of points in space isoccupied or free. Octomap provides us Full 3D model. 

B.  Stable Data Structure:  The data structures used to store and update themap  is  of  critical  importance.   Consider  the  situation  where  we  assigna binary (1/0 for occupied/free) label to every point in the point cloud,the look up table would be memory inefficient and difficult to accurately update.  Octomap provides for an elegant alternative with an efficient datastructure for occupancy updates.

## b) Signed Distance Functions

1. How do we determine object surfaces using SDF?
2. How do we aggregate views from multiple cameras? (just a general overview is fine)
3. Which preserves details better? Voxels or SDF? Why?
4. What’s an advantage of SDF over a point cloud?


### SOLUTION
1. For a given SDF function $\theta(x): R^3 \rightarrow R$. This function returns for any point $x \in R^3 $ the  signed  distance  from   to  the surface. \
If $x$ is on the surface then $\theta(x) = 0$ .\
Ref:- http://www.roboticsproceedings.org/rss09/p35.pdf  \
Note:- For discrete representations of Implicit Functions, the location of the interface ,the $\phi(x)= 0$ zero iso-contour is interpolated from the known values of $\phi$ at the data points using Marching Cubes algorithm.
Ref:- http://faculty.missouri.edu/duanye/course/cs8620-spring-2017/lecture-notes/3a-implicit-geometry.pdf 



2. The aggregate views from multiple cameras is used for the camera motion estimation to find the affine transformations which convert the local frame's point clouds to global coordinate and integrate them into a final point cloud for a object representation.  These affine  transformation represent the movement of camera from the first frame to the last frame. \
Ref:- https://thesai.org/Downloads/IJARAI/Volume5No9/Paper_5-WSDF_Weighting_of_Signed_Distance_Function.pdf


3. SDF has gradient and distance information inherently available. Voxel-based approaches do not preserve fine shape details since when rendered their normals are not smooth. SDF scale beautifully because of smooth interpolation between samples. 


4. Pointclouds are not suitable for producing smooth surfaces and there is no simple representation of free or unknown space. While in SDF, surface looks very smooth due to sub-pixel level accuracy, which giver better visualization. SDF provides us an ability to scale a 3D model. \
Ref:- https://openaccess.thecvf.com/content_CVPR_2019/papers/Park_DeepSDF_Learning_Continuous_Signed_Distance_Functions_for_Shape_Representation_CVPR_2019_paper.pdf

# References and Resources

1. Gimbal locks and quaternions: https://youtu.be/YF5ZUlKxSgE
2. Exponential map: 
    1. 3 Blue 1 Brown: https://youtu.be/O85OWBJ2ayo
    2. Northwestern Robotics: https://youtu.be/v_KBHaG0mas
3. Bunny ply is taken from: http://graphics.im.ntu.edu.tw/~robin/courses/cg03/model/